---
# Source: spark/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-spark-secret
  namespace: "default"
  labels:
    app.kubernetes.io/name: spark
    helm.sh/chart: spark-7.1.1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
