---
# Source: spark/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-spark
  namespace: "default"
  labels:
    app.kubernetes.io/name: spark
    helm.sh/chart: spark-7.1.1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
